### ISSUE TITLE
Unable to use iOS version of framework in a project

### ISSUE THREAD

**Issue by brendanballon** [zydeco/NBTKit#2]
With the project properly imported into my project, it builds successfully and runs but immediately crashes and give the error:

`dyld: Library not loaded: @loader_path/../Frameworks/NBTKit.framework/NBTKit
  Referenced from: /private/var/containers/Bundle/Application/EA080AD7-A261-4DFB-84ED-5A30A9333128/Level Explorer.app/Level Explorer
  Reason: image not found`

**Comment by zydeco** [comment]
The install path was wrong on the iOS target, it should be fixed in a1e53ef
